name: paradrop-voice
version: 0.1
summary: Enable voice output and recognition for Paradrop nodes.
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  paradrop-voice:
    command: paradrop-voice
#    daemon: simple
    restart-condition: always
    plugs:
      - network
      - pulseaudio

parts:
  paradrop-voice:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libpocketsphinx3
      - libpulse0
    organize:
      # For some reason, the libpulsecommon .so file could not be found in its
      # default install location, so move it to a place where it can be found.
      usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so: usr/lib/x86_64-linux-gnu/libpulsecommon-8.0.so
